services:
  front-ofertando:
    build:
      context: .
    container_name: front-ofertando-app
    ports:
      - '${FRONTEND_PORT:-5173}:${PORT:-3000}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
